"""fix profiles

Revision ID: 03359c243184
Revises: ac9f72992c69
Create Date: 2025-09-19 12:30:58.278882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03359c243184'
down_revision: Union[str, Sequence[str], None] = 'ac9f72992c69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'images', ['checksum'])
    op.drop_constraint(op.f('profiles_avatar_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'images', ['avatar_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_avatar_id_fkey'), 'profiles', 'images', ['avatar_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'images', type_='unique')
    # ### end Alembic commands ###
