"""move field username to profiles and add ondelete to relationships

Revision ID: 143675703e70
Revises: 03359c243184
Create Date: 2025-10-14 18:07:56.047542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143675703e70'
down_revision: Union[str, Sequence[str], None] = '03359c243184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('relationships_relation_id_fkey'), 'relationships', type_='foreignkey')
    op.create_foreign_key(None, 'relationships', 'relationships_groups', ['relation_id'], ['relation_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.create_foreign_key(op.f('relationships_relation_id_fkey'), 'relationships', 'relationships_groups', ['relation_id'], ['relation_id'])
    # ### end Alembic commands ###
