"""add images table

Revision ID: 29685cd2b610
Revises: e2880873f4f6
Create Date: 2025-09-19 08:00:25.581827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29685cd2b610'
down_revision: Union[str, Sequence[str], None] = 'e2880873f4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('alt_text', sa.String(length=150), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('relationships', 'relation_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relationships', 'relation_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_table('images')
    # ### end Alembic commands ###
