"""Add nullable=False to role

Revision ID: 7070da332834
Revises: 581cff156097
Create Date: 2025-10-17 16:37:56.257742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7070da332834'
down_revision: Union[str, Sequence[str], None] = '581cff156097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('superuser', 'admin', 'member', name='userrole'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('superuser', 'admin', 'member', name='userrole'),
               nullable=True)
    # ### end Alembic commands ###
