"""change owner_id column name to profile_id in members;


Revision ID: 7fa0d4832db7
Revises: b01fd3cbd451
Create Date: 2025-11-23 14:37:29.995903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa0d4832db7'
down_revision: Union[str, Sequence[str], None] = 'b01fd3cbd451'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('members_owner_id_fkey'), 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('members', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key(op.f('members_owner_id_fkey'), 'members', 'profiles', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('members', 'profile_id')
    # ### end Alembic commands ###
