"""Add profiles and followers, followings models

Revision ID: 95c87ec968f9
Revises: d45f9a65a874
Create Date: 2025-09-05 15:28:28.718352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95c87ec968f9'
down_revision: Union[str, Sequence[str], None] = 'd45f9a65a874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_type', sa.Enum('public', 'private', name='profiletype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('followers_following_association',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id', name='followers_following_pk')
    )
    op.create_unique_constraint(None, 'refresh_sessions', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'refresh_sessions', type_='unique')
    op.drop_table('followers_following_association')
    op.drop_table('profiles')
    # ### end Alembic commands ###
