"""add avatar to profiles

Revision ID: ac9f72992c69
Revises: 29685cd2b610
Create Date: 2025-09-19 08:08:48.354737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac9f72992c69'
down_revision: Union[str, Sequence[str], None] = '29685cd2b610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'profiles', 'images', ['avatar_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.drop_column('profiles', 'avatar_id')
    # ### end Alembic commands ###
