"""Fix column name in members and add membership_id

Revision ID: b01fd3cbd451
Revises: 0ed1c779f803
Create Date: 2025-11-21 12:09:08.573602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b01fd3cbd451'
down_revision: Union[str, Sequence[str], None] = '0ed1c779f803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('members', sa.Column('membership_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('members_profile_id_fkey'), 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'memberships', ['membership_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'members', 'profiles', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('members', 'profile_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key(op.f('members_profile_id_fkey'), 'members', 'profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.drop_column('members', 'membership_id')
    op.drop_column('members', 'owner_id')
    # ### end Alembic commands ###
