"""add relationships aggregate

Revision ID: c264f2cf1a0b
Revises: 95c87ec968f9
Create Date: 2025-09-09 16:05:48.595575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c264f2cf1a0b'
down_revision: Union[str, Sequence[str], None] = '95c87ec968f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships_groups',
    sa.Column('relation_id', sa.Integer(), nullable=False),
    sa.Column('version_num', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('relation_id', sa.Integer(), nullable=True),
    sa.Column('is_followed', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_id'], ['relationships_groups.relation_id'], ),
    sa.PrimaryKeyConstraint('id', 'follower_id', 'following_id'),
    sa.UniqueConstraint('id')
    )
    op.drop_table('followers_following_association')
    op.create_unique_constraint(None, 'profiles', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.create_table('followers_following_association',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['profiles.id'], name=op.f('followers_following_association_follower_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['profiles.id'], name=op.f('followers_following_association_following_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'following_id', name=op.f('followers_following_pk'))
    )
    op.drop_table('relationships')
    op.drop_table('relationships_groups')
    # ### end Alembic commands ###
