"""add username column to profiles

Revision ID: d9418cdd4850
Revises: c264f2cf1a0b
Create Date: 2025-09-09 20:31:00.948036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9418cdd4850'
down_revision: Union[str, Sequence[str], None] = 'c264f2cf1a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'profiles', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_column('profiles', 'username')
    # ### end Alembic commands ###
