"""add members and memberships table

Revision ID: e04d2ce6b77c
Revises: 2e694e5f757b
Create Date: 2025-11-20 17:23:05.864042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04d2ce6b77c'
down_revision: Union[str, Sequence[str], None] = '2e694e5f757b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='memberrole'), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('can_change_organization_info', sa.Boolean(), nullable=False),
    sa.Column('can_invite_members', sa.Boolean(), nullable=False),
    sa.Column('can_create_shows', sa.Boolean(), nullable=False),
    sa.Column('can_add_venue_requests', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('version_num', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memberships')
    op.drop_table('members')
    # ### end Alembic commands ###
