"""add autoincrement=false to relationships groups

Revision ID: e2880873f4f6
Revises: 986e3863eb8c
Create Date: 2025-09-12 16:12:03.710105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2880873f4f6'
down_revision: Union[str, Sequence[str], None] = '986e3863eb8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships_groups',
    sa.Column('relation_id', sa.String(length=50), autoincrement=False, nullable=False),
    sa.Column('version_num', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('relation_id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('relation_id', sa.String(length=50), nullable=True),
    sa.Column('is_followed', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['following_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_id'], ['relationships_groups.relation_id'], ),
    sa.PrimaryKeyConstraint('id', 'follower_id', 'following_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('relationships_groups')
    # ### end Alembic commands ###
